Dasharo UEFI Secure Boot support for OVMF
Dasharo/edk2 pull request #104
Opened 2023-10-26 13:12 UTC by pietrushnic

2023-10-26 14:34 UTC, miczyg1 requested changes

2023-10-26 14:34 UTC, miczyg1 commented on OvmfPkg/PlatformPei/Platform.c
> +
This is only a part of the verification. Following the FVH there is also NVAR storage header which should be validated too.

2023-10-26 14:34 UTC, miczyg1 commented on OvmfPkg/PlatformPei/Platform.c
> +  Status = ValidateFvHeader (FwVolHeader);
This should probably be put before line `if (CmosRead8 (0xF) == 0xFE) {` and use the variable mBootMode:

```C
  //
  // Set BootMode based on FV header state
  //
  Status = ValidateFvHeader (FwVolHeader);

  if (EFI_ERROR (Status)) {
    mBootMode = BOOT_WITH_DEFAULT_SETTINGS;
    DEBUG ((DEBUG_INFO, "BootMode: Boot with default settings\n"));
  } else {
    mBootMode = BOOT_ASSUMING_NO_CONFIGURATION_CHANGES;
    DEBUG ((DEBUG_INFO, "BootMode: Boot boot assuming no configuration changes\n"));
```

2023-10-26 22:42 UTC, pietrushnic commented
@miczyg1 These commits are no longer valid since your new code implementing UEFI Secure Boot works out of the box. No modification is needed. I continue to work on UEFI Secure Boot as part of #106 and will push modifications there if needed.

2023-10-26 22:43 UTC, closed without merging

2023-10-26 22:46 UTC, macpijan commented
@pietrushnic Have you checked if clearing/resetting keys also works as expected?

2023-10-27 11:42 UTC, pietrushnic commented
@macpijan I didn't get too far. I can see that I can enable/disable secure boot in Custom Mode after resetting keys (aka provisioning default one). The next step would be to check if I can install OS in UEFI Secure Boot-aware way.