Autoboot timeout fix
Dasharo/edk2 pull request #94
Opened 2023-10-17 07:23 UTC by filipleple

2023-10-17 08:08 UTC, miczyg1 requested changes

2023-10-17 08:08 UTC, miczyg1 commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +  if (Action == EFI_BROWSER_ACTION_DEFAULT_FIRMWARE) {
```suggestion
  if (Action == EFI_BROWSER_ACTION_RESET_TO_DEFAULT) {
```

2023-10-17 08:08 UTC, miczyg1 commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +    CurrentFakeNVMap->BootTimeOut = defaultValue
You have to filter for Auto Boot TImeout QuestionID. For other it has to return EFI_UNSUPPORTED.

The value is being set using the `IN        EFI_IFR_TYPE_VALUE                     *Value,` parameter. So you should probably do `Value->u16 = PcdGet16 (PcdPlatformBootTimeOut);` If this doesn't work, then `CurrentFakeNVMap->BootTimeOut =  PcdGet16 (PcdPlatformBootTimeOut);` will probably be the way

2023-10-17 08:08 UTC, miczyg1 commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +    HiiSetBrowserData (&mBootMaintGuid, mBootMaintStorageName, sizeof (BMM_FAKE_NV_DATA), (UINT8 *) CurrentFakeNVMap, NULL);
This function is called at the end of BootMaintCallback . The value will be saved when the save hotkey is pressed (also handled in separate action most likely).

2023-10-17 08:08 UTC, miczyg1 commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +    return EFI_SUCCESS;
No need to return here as the other IF branches will protect fro executing any other code, i.e. if `Action` is `EFI_BROWSER_ACTION_RESET_TO_DEFAULT`, it will not have any other value in given call of BootMaintCallback unless you explicitly change it.

2023-10-17 08:39 UTC, filipleple commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +  if (Action == EFI_BROWSER_ACTION_DEFAULT_FIRMWARE) {
@miczyg1 It won't compile with EFI_BROWSER_ACTION_RESET_TO_DEFAULT. Does that mean I'm missing something or is EFI_BROWSER_ACTION_REQUEST_RESET, as suggested by the compiler, valid?

2023-10-17 09:19 UTC, filipleple commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +    CurrentFakeNVMap->BootTimeOut = defaultValue
@miczyg1 both `Value->u16 = PcdGet16 (PcdPlatformBootTimeOut);` and `CurrentFakeNVMap->BootTimeOut =  PcdGet16 (PcdPlatformBootTimeOut);` still cause the timeout value to be restored to `0`. Could the default value returned by `PcdGet16` really be `0`?

2023-10-18 09:06 UTC, miczyg1 commented on MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
> +  if (Action == EFI_BROWSER_ACTION_DEFAULT_FIRMWARE) {
Actually the proper define for that is `EFI_BROWSER_ACTION_DEFAULT_STANDARD` and `EFI_BROWSER_ACTION_DEFAULT_MANUFACTURING`

2023-10-18 09:46 UTC, miczyg1 commented
I have prepared an alternative approach how to add default value support for dynamically generated IFR opcodes:
https://github.com/Dasharo/edk2/pull/96

It looks like the last parameter of HiiCreateNumericOpCode can take any Opcode which is appended to the primary opcode generated by HiiCreateNumericOpCode. In this case I have created a Default value opcode with HiiCreateDefaultOpCode

2023-10-20 21:16 UTC, miczyg1 commented
Merged the https://github.com/Dasharo/edk2/pull/96 so this PR is obsolete.

2023-10-20 21:16 UTC, closed without merging